---
- name: Setup Webserver
  hosts: websvrgrp
  become: yes
  tasks:
    - name: Install Apache httpd
      yum:
              name: httpd
              state: present
    - name: Start & Enable httpd
      service:
              name: httpd
              state: started
              enabled: yes
    - name: Copy
      copy:
              src: index.html
              dest: /var/www/html/index.html
              owner: root
              group: root
              mode: '0644'
              backup: yes

- name: Setup DBServer
  hosts: dbsvrgrp 
  become: yes
  #  vars:
  #       dbname: groups
  #       dbuser: devops
  #       dbpass: admin123
  tasks:
          - debug:
                  var: dbname

          - debug:
                  msg: "Value of dbuser is {{dbuser}}"

          - name: Install MySQL server
            yum:
                    name: mariadb-server
                    state: present
          - name: Install Python MySQL
            yum:
                    name: MySQL-python
                    state: present

          - name: Install MySQL server
            yum:
                    name: mariadb-server
          - name: Start & Enable mariadb service
            service:
                    name: mariadb
                    state: started
                    enabled: yes
          - name: Create a new database with name 'account'
            mysql_db:
                    name: "{{dbname}}"
                    state: present

          - name: Create database user with name 'bob'
            mysql_user:
              name: "{{dbuser}}"
              password: "{{dbpass}}"
              priv: '*.*:ALL'
              state: present
